### ISSUE TITLE
[1.15.2][spigot] NoSuchMethodError: org.bukkit.entity.Mob.setAware

### ISSUE THREAD

**Issue by pedxyuyuko** [NyaaCat/Yasui#11]
Info:
- MC-Version: 1.15.2
- Server: Spigot
- Installed Plugin: LangUtils | NyaaCore | Yasui

Error:
![image](https://user-images.githubusercontent.com/39913604/77138593-9894da80-6aad-11ea-91ad-6fa4c8679da6.png)

```
java.lang.NoSuchMethodError: org.bukkit.entity.Mob.setAware(Z)V
        at cat.nyaa.yasui.other.Utils.nerfAI(Utils.java:197) ~[?:?]
        at cat.nyaa.yasui.other.Utils.setAI(Utils.java:184) ~[?:?]
        at cat.nyaa.yasui.other.Utils.checkLivingEntity(Utils.java:91) ~[?:?]
        at cat.nyaa.yasui.task.ChunkTask.run(ChunkTask.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
```

Thanks for all people that made this awesome proj

**Comment by nywek** [comment]
Maybe related:

```
[08:50:25] [Server thread/ERROR]: Could not pass event EntityDeathEvent to yasui v7.0.69
org.bukkit.event.EventException: null
...
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.entity.LivingEntity.getChunk()'
	at cat.nyaa.yasui.listener.EntityListener.onMobDeath(EntityListener.java:84) ~[?:?]
```

[LivingEntity](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html) (spigot-api 1.15.2) does not have a method `getChunk()`

**Comment by pedxyuyuko** [comment]
> Maybe related:
> 
> ```
> [08:50:25] [Server thread/ERROR]: Could not pass event EntityDeathEvent to yasui v7.0.69
> org.bukkit.event.EventException: null
> ...
> Caused by: java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.entity.LivingEntity.getChunk()'
> 	at cat.nyaa.yasui.listener.EntityListener.onMobDeath(EntityListener.java:84) ~[?:?]
> ```
> 
> [LivingEntity](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html) (spigot-api 1.15.2) does not have a method `getChunk()`

I think 1.15.2 has a lot of changes

**Comment by phoenixlzx** [comment]
Spigot / paper version?

**Comment by pedxyuyuko** [comment]
> Spigot / paper version?

MC: 1.15.2
Spigot: spigot-c574e08
API: 1.15.2-R0.1

**Comment by ReinWD** [comment]
upgrade your server jar because this method is added halfway.
I only know that paperMC build 120 or after contains that method. 
Use your buildtool.jar to fetch a newer version of Spigot, or download a new PaperMC build at 
https://papermc.io/downloads

**Comment by pedxyuyuko** [comment]
> upgrade your server jar because this method is added halfway.
> I only know that paperMC build 120 or after contains that method.
> Use your buildtool.jar to fetch a newer version of Spigot, or download a new PaperMC build at
> https://papermc.io/downloads

Thanks for that! It solved the problem of ``NoSuchMethodError: org.bukkit.entity.Mob.setAware`` but there is a new problem like @Fear837 said: 

```
Could not pass event EntityDeathEvent to yasui v7.0.69
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:721) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1545) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.entity.LivingEntity.getChunk()'
        at cat.nyaa.yasui.listener.EntityListener.onMobDeath(EntityListener.java:84) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        ... 23 more
[10:02:04] [Server thread/ERROR]: Could not pass event EntityDeathEvent to yasui v7.0.69
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:721) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1545) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.entity.LivingEntity.getChunk()'
        at cat.nyaa.yasui.listener.EntityListener.onMobDeath(EntityListener.java:84) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
        ... 23 more
```

**Comment by ReinWD** [comment]
> jdk.internal.reflect.NativeMethodAccessorImpl.invoke

alright, I'll check it soon. Maybe hours later.

**Comment by pedxyuyuko** [comment]
> > jdk.internal.reflect.NativeMethodAccessorImpl.invoke
> 
> alright, I'll check it soon. Maybe hours later.

I think there is no method called ``getChunk`` in org.bukkit.Chunk org.bukkit.entity.LivingEntity so the reflection failed?

**Comment by ReinWD** [comment]
Spigot is a ***Compile Only*** Library.
It means that the version while **compiling**  may be different with the one in your configuration..
Just got home and checking out what happend in newer version of Spigot.

**Comment by ReinWD** [comment]
Figured out why.
Method `org.bukkit.entity.LivingEntity.getChunk()` is located in PaperMC's API.
We'll use Spigot compatible call in next dev build.

BTW, suggest to try PaperMC.

**Comment by pedxyuyuko** [comment]
> Figured out why.
> Method `org.bukkit.entity.LivingEntity.getChunk()` is located in PaperMC's API.
> We'll use Spigot compatible call in next dev build.
> 
> BTW, suggest to try PaperMC.

Thanks! I will try Paper.

**Comment by pedxyuyuko** [comment]
Thanks for all! Should I close this issue?

**Comment by ReinWD** [comment]
Sure. I'll fix this.

**Comment by ReinWD** [comment]
Building latest Spigot and testing.
New Dev build will come in few ten minutes.

**Comment by pedxyuyuko** [comment]
> Building latest Spigot and testing.
> New Dev build will come in few ten minutes.

Awesome job!
