### ISSUE TITLE
Add support for MC 1.15.2

### ISSUE THREAD

**Issue by James76931** [NyaaCat/Yasui#7]
When trying to run the plugin on Paper (build 77, mc 1.15.2) I get the following error which prevents the plugin from loading. I am using the latest build of Yasui in the 1.15 branch.

`[09:57:00 INFO]: [NyaaCore] Enabling NyaaCore v7.1.350
>[09:57:00 ERROR]: [NyaaCore] CraftBukkit Mapping changed! Use with caution!
>[09:57:00 INFO]: [yasui] Enabling yasui v7.0.x
>[09:57:01 INFO]: [yasui] Now using language: en_US
>[09:57:01 INFO]: [yasui] Now using language: en_US
>[09:57:01 ERROR]: Error occurred while enabling yasui v7.0.x (Is it up to date?)
java.lang.NoClassDefFoundError: com/udojava/evalex/Function
at cat.nyaa.yasui.Yasui.onEnable(Yasui.java:42) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-77]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.2.jar:git-Paper-77]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.2.jar:git-Paper-77]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.2.jar:git-Paper-77]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.2.jar:git-Paper-77]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-77]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:291) ~[patched_1.15.2.jar:git-Paper-77]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-77]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.udojava.evalex.Function
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150) ~[patched_1.15.2.jar:git-Paper-77]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.15.2.jar:git-Paper-77]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 10 more
>.... [09:57:01 INFO]: [yasui] Disabling yasui v7.0.x`

**Comment by phoenixlzx** [comment]
try replace your NC
https://ci.nyaacat.com/job/NyaaCore/lastSuccessfulBuild/artifact/build/libs/NyaaCore-mc1.15.1-7.1.350-shadowed.jar

**Comment by James76931** [comment]
That fixed it. Thanks! :)
